import os
from building import *

cwd = GetCurrentDir()
name = os.path.split(cwd)[-1]

src = Glob('*.c')

CPPPATH = [cwd+'/include']
LOCAL_CPPPATH = [cwd+'/include/driver']

group = DefineGroup(name, src, depend = [''], CPPPATH = CPPPATH, LOCAL_CPPPATH = LOCAL_CPPPATH)

Return('group')
