import os
from building import *

cwd = GetCurrentDir()
name = os.path.split(cwd)[-1]

src = Glob('library/*.c')+Glob('port/*.c')

CPPPATH = [cwd+'/include',cwd+'/port/include']

group = DefineGroup(name, src, depend = [''], CPPPATH = CPPPATH)

Return('group')
